### ISSUE TITLE
Tweak CSS

### ISSUE THREAD

**Issue by XhmikosR** [bryanbraun/anchorjs#10]
1. I believe we should use a less generic class for the anchor class like maybe `anchorjs-link`
2. I don't think we need to use adjoining classes; we can just use `.anchorjs-link` instead of `a.anchorjs-link`.
3. We should specify `aria-hidden="true"` for the icon-link `span`. Or even better, add a title in the `a` tag.

Let me know your thoughts <3

**Comment by bryanbraun** [comment]
I totally agree on items 1 & 2. In fact, we should make that `icon-link` class less generic too (in case somebody is using this on a site with other icomoon icons). I'll put up a PR for those soon.

I had a lot of thoughts on the accessibility topic so I split it off into [its own issue](https://github.com/bryanbraun/anchorjs/issues/12) and left [my comments](https://github.com/bryanbraun/anchorjs/issues/12#issuecomment-68500388) there.

**Comment by bryanbraun** [comment]
Pull request here, in case anybody wants to review and weigh in: https://github.com/bryanbraun/anchorjs/pull/13

If nobody opposes, I'll merge in the next day or two.
