### ISSUE TITLE
Title attribute?

### ISSUE THREAD

**Issue by catchmyfame** [bryanbraun/anchorjs#100]
How about an option to add a `title` attribute to the links generated? One way to implement this might be to set a data attribute on the target element(s) with the content for the title attribute, which the script could read and insert into the link. Another possibility could be to set a default title option to use in all anchors generated.

**Comment by bryanbraun** [comment]
That's an interesting idea. What do you think the benefit of including a title would be?

**Comment by catchmyfame** [comment]
I think (know actually from someone asking me about it) that some users don't understand what these links do or represent. Having a title attribute would allow us to have some descriptive text appear when hovering over the links. For example, a user hovers over an anchorjs enabled heading, the link icon appears, and when they hover over it, the title attribute would display text like, "This link can be bookmarked or shared to jump directly to this section of the page". Just a thought. Thanks!

**Comment by catchmyfame** [comment]
Just pushed a PR for this feature. https://github.com/bryanbraun/anchorjs/pull/102

**Comment by bryanbraun** [comment]
I merged the PR you pushed and added the changes I mentioned in #102.

The new option has also been added to the docs. 👍
