### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by stephenbe** [bryanbraun/anchorjs#104]
Hey @bryanbraun 

Is it possible to add an automatic prefix for Id's generated?

Something like this : 

anchors.add('h3');
anchors.prefix('foo_', 'h3');

Would result in this : 

`<h1 id="foo_lorem">Lorem</h1>`

That or able to hook in the way the plugin decides how to name Ids

Thanks!

**Comment by bryanbraun** [comment]
@stephenbe, thanks for asking.

There currently isn't a way to hook into the ID names outside of the new `anchors.options.base` feature, (and that probably won't give you the kind of prefixes you are looking for).

Do you want to add prefixes to prevent url name conflicts or is it for branding purposes?

If it's the former, AnchorJS already has a mechanism in place to prevent conflicts. It increments a number in the ID, like `example`, `example-1`, `example-2`, etc.

**Comment by bryanbraun** [comment]
I'm deciding not to support anchor prefixes for branding purposes alone (to err on the side of simplicity). We already have a solution in place for url conflicts, so unless there are any other reasons to support this, I'm going to close it for now. 👍

**Comment by mahrud** [comment]
I've run across a problem unrelated to conflicts or branding which requires prefixes to the auto-generated IDs (i.e. not just the basename). I have a static website which is populated at runtime based on the hash in the url, so for instance `/docs/#blah` loads `blah.json` and populates the page, then calls `anchors.add()` to generate anchor links for the generated headings, so the url that the anchors go to is something like `/docs/#blah#example-1`. I can handle taking this url and generating the same content as `/docs/#blah`, but now the ID on the heading is still `#example-1`, so it's not going to jump to that. If I could set the ID to be `#blah-example-1` then  I believe this could work.
