### ISSUE TITLE
Make anchorjs available via NPM and us NPM to manage linting/minification

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#11]
This issue was created from [this comment](https://github.com/bryanbraun/anchorjs/pull/7#issue-52837762):

> How about using grunt and add uglify and lint stuff? Or we could just go with npm scripts to handle everything which should be cleaner for such a small project anyway.

> Also, how about making a new release after this gets merged?

Initial work has been started here: https://github.com/XhmikosR/anchorjs/compare/npm

**Comment by bryanbraun** [comment]
@XhmikosR, this PR looks like a great start. I have a few questions:

1. What's the value in having a `_config.yml` file here? Is it useful for people who use this project on their Jekyll sites? Wouldn't those sites provide their own `_config.yml` files?
2. Why would we use both ESLint and JSHint? Is there anything JSHint does that ESLint can't also do?

I've gone ahead and enabled TravisCI for this repo, so tests should start running once we push the `.travis.yml` file up.

**Comment by XhmikosR** [comment]
1. The reason for the _config.yml is for local development. Being that node_modules has a lot of files/folders, it makes page generation slow without excluding it.
2. Well, I'm not sure ESLint is now on par with JSHint, i.e. covers all the checks JSHint has that is why I still use it in addition to JSHint.

**Comment by bryanbraun** [comment]
1. I'm still trying to understand why we'd need to exclude `node_modules` in this project specifically. A person including AnchorJS in their jekyll site won't be pulling in the npm dependencies to build the minified version from scratch, will they? Even if they were, can't each Jekyll site that integrates AnchorJS exclude `node_modules` in their own `_config.yml` file? I'd prefer not to include framework-specific config in this project, unless there's a good reason. I'm looking at other projects that are often included in Jekyll sites (like [jQuery](https://github.com/jquery/jquery)), and I don't see any examples of the javascript library itself providing it's own `_config.yml` for excluding `devDependencies`.

 2. That makes sense. When I compare the .jshintrc and the .eslintrc files, it looks like several of the rules that are being checked are redundant. For example both files define these:
```js
{
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "quotmark": "single", // in .eslintrc: "quotes": [2, "single"],
}
```
Can we just remove the redundant rules from .jshintrc? If we're using both linters with the idea that we're falling back on jshint where eslint is lacking, then I'd feel better about only using jshint to check the rules that eslint doesn't yet support.

3. Also, should `"name": "Anchor.JS"` be lowercase? At a glance, it looks like the package names I'm seeing in the npm registry are all lowercase.

Thanks for your patience. :)

**Comment by XhmikosR** [comment]
1. Personally, I have no interest in digging into this so much at this point; I have a setup that works for both ESLint and JSHint and that's enough for me. You can do any changes you want yourself later.
2. See 1.
3. It doesn't matter, it can be anything. Again, you can change it before you publish the package.

**Comment by bryanbraun** [comment]
Fair enough. I'll prepare to merge this and add a commit or two of minor adjustments on the items I mentioned.

Thanks for setting this up!
