### ISSUE TITLE
Replace PhantomJS with Headless Chrome

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#114]
We currently use PhantomJS for our tests, but it's deprecated. We should switch to using headless chrome.

This shouldn't be that difficult. We probably just need to remove `phantomjs-prebuilt`, replace `karma-phantomjs-launcher` with something like [`karma-chrome-launcher`](https://github.com/karma-runner/karma-chrome-launcher), and get it configured correctly.

**Comment by Gobinath-Manokaran** [comment]
@bryanbraun I can do take up this

**Comment by bryanbraun** [comment]
Fixed in #115. 👍
