### ISSUE TITLE
Add the scroll-margin-top technique to the docs

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#137]
The AnchorJS docs have [a section](https://www.bryanbraun.com/anchorjs/#pages-with-a-sticky-navbar) about how to prevent overlap when you have a sticky nav-bar.

I just learned about a new technique for this: https://twitter.com/hakimel/status/1257252729128435712

Event better... combining this with a `:target` selector: https://www.bram.us/2020/03/01/prevent-content-from-being-hidden-underneath-a-fixed-header-by-using-scroll-margin-top/

We should include this new technique in the docs. We can remove the existing technique, once all the major browsers support the new technique (it looks like we're still waiting on Safari, at the time that I'm writing this).

**Comment by tusharck** [comment]
Can i be assigned to the issue?

**Comment by tusharck** [comment]
I made a PR please review.
