### ISSUE TITLE
Copy the link to clipboard instead of jumping to it 

### ISSUE THREAD

**Issue by kapooramit** [bryanbraun/anchorjs#139]
Google docs does it very nicely and I see it more beneficial in product documentation context:

[https://developers.google.com/docs/api/reference/rest/v1/documents#top_of_page](url)

How can I achieve the same behavior without changing **anchorjs**? Is there an option to toggle the behavior between copy link and jump to link?

Thanks.

**Comment by bryanbraun** [comment]
Super interesting!

I've been thinking about this. It's definitely possible for developers to write some code that works together with AnchorJS to achieve this affect:

```js
// run this after running AnchorJS
let anchorjsLinks = document.querySelectorAll(".anchorjs-link");

anchorjsLinks.forEach(el => {
  el.addEventListener("click", event => {
    event.preventDefault();
      // add custom "copy to clipboard" code
  });
});
```

As for adding it to the AnchorJS, I'm thinking I'll hold off on that for a few reasons:

* "Copy to clipboard" code [can be complex due to adding fallbacks](https://stackoverflow.com/a/30810322/1154642) for browsers that [might not fully support the new Clipboard API](https://caniuse.com/#feat=clipboard). I'd hate to add the bloat of those fallbacks to AnchorJS for people who don't use this feature, or for people who do, but don't need to support those older browsers.
* This feature would require me to add a number of new UI elements which raises some new questions (see below for screenshot showing the hover-state and confirmation message). What would the default styles need to be? Can authors override them? What z-index is appropriate?
![image](https://user-images.githubusercontent.com/1256329/83672802-de3d4b80-a5a4-11ea-8429-639a2d9001aa.png)

In general it doesn't feel worth it to add this complexity for a niche feature right now. Some good next-steps might be to put together a gist for adding this functionality, so people who are interested can copy/paste into their own code. This could even take the form of a sibling package or plugin (like `anchorjs-copy-to-clipboard`). Feel free to take a pass at one of those if you're interested (I probably won't do it unless I see more demand for a feature like this).

Anyways, if lots of people end up using a workaround like that, then maybe then it would make more sense to pull it into the main project. 👍

**Comment by kapooramit** [comment]
Thanks Bryan! :-)

I am using ClipboardJS for code blocks and it works very well. Now, when I try using it for the anchorjs links, it is not doing anything. Would you know why?

Here is the code I added in addition to what you shared:

```
<script>
        anchors.add();
      
       // add deep anchor link href value to data-clipboard-text attribute for ClipboardJS to use. 
        for (var r=0; r < document.getElementsByClassName("anchorjs-link").length; r++) {
          var danchorid = "clipboard-200".concat(r);   //custom id string
          document.getElementsByClassName("anchorjs-link")[r].setAttribute('id',danchorid);
          var danchorhref = document.getElementById(danchorid).href;
          document.getElementById(danchorid).setAttribute('data-clipboard-text',danchorhref);
          document.getElementById(danchorid).setAttribute('class','anchorjs-link lover');
        }

        // run this after running AnchorJS
        let anchorjsLinks = document.querySelectorAll(".anchorjs-link");

        anchorjsLinks.forEach(el => {
          el.addEventListener("click", event => {
            event.preventDefault();
            // add custom "copy to clipboard" code
            var danchorclipboard = new ClipboardJS('.anchorjs-link');       
          });
        });
</script>
```
 
Once the page is loaded, the HTML of the anchor is as follows:

```
<a class="anchorjs-link lover" aria-label="Anchor" data-anchorjs-icon="" href="#Overview-AnalysisCapabilities" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;" id="clipboard-2001" data-clipboard-text="https://baseURL#SIProandPIProOverview-AnalysisCapabilities">
</a>
```

**Comment by bryanbraun** [comment]
@kapooramit, hey I was able to take a closer look at this today.

I wouldn't recommend changing AnchorJS to make it output buttons. I think you can get what you want, just by changing the Clipboard.js code a bit. Here's an example I put together that seems to work for me: https://codepen.io/bryanbraun/pen/PoZZbXm

Looking at your code, I think the problem was this part:

```js
anchorjsLinks.forEach(el => {
  el.addEventListener("click", event => {
    event.preventDefault();
    // add custom "copy to clipboard" code
    new ClipboardJS(".anchorjs-link");       
  });
});
```

We can't run `new ClipboardJS` here, because that line doesn't do the copy action itself... it just adds event listeners for future clicks. We want those listeners during page load, right after the anchors are added (not every time we click on a link).

Anyways, take a look at my codepen example and let me know if that helps!

**Comment by bryanbraun** [comment]
I'm gonna close this for now, but let me know if you still think there's an issue with anchor-js that needs to be discussed here. 👍

**Comment by kapooramit** [comment]
Thanks Brian. I am sorry that I could not respond earlier. I am trying to access the codeppen but it doesn't seem to be there anymore.

**Comment by bryanbraun** [comment]
@kapooramit, yeah sorry I searched around but I can't find it anymore. 😞

**Comment by kapooramit** [comment]
I will live with the button change then until I figure it out myself or get into an issue. Thanks Bryan!

**Comment by aadibajpai** [comment]
> Super interesting!
> 
> I've been thinking about this. It's definitely possible for developers to write some code that works together with AnchorJS to achieve this affect:
> 
> ```js
> // run this after running AnchorJS
> let anchorjsLinks = document.querySelectorAll(".anchorjs-link");
> 
> anchorjsLinks.forEach(el => {
>   el.addEventListener("click", event => {
>     event.preventDefault();
>       // add custom "copy to clipboard" code
>   });
> });
> ```

I'm trying this out and it appears that preventDefault() not only disables the scrolling to top behaviour but also the element disappearing when not hovering behaviour. So once I click, it does copy it to the clipboard perfectly but also leaves the symbol visible even when not hovering.

**Comment by kapooramit** [comment]
It worked and still works perfectly for me. Something else is going on in your code.

**Comment by bryanbraun** [comment]
@aadibajpai, yeah, my code snippet is just an example to demonstrate the approach. I haven't actually tested it anywhere. It may need some refinements before using on a production site. 👍

**Comment by aadibajpai** [comment]
> It worked and still works perfectly for me. Something else is going on in your code.

nah, removing that line makes it work well enough so I suspect it's either that or something else not playing well with it, I'm using navigator.clipboard.writeText() btw

**Comment by y377** [comment]
> 超级有趣！
> 
> 我一直在想这个。开发人员完全可以编写一些与 AnchorJS 一起工作的代码来实现这种效果：
> 
> ```js
> // run this after running AnchorJS
> let anchorjsLinks = document.querySelectorAll(".anchorjs-link");
> 
> anchorjsLinks.forEach(el => {
>   el.addEventListener("click", event => {
>     event.preventDefault();
>       // add custom "copy to clipboard" code
>   });
> });
> ```
> 
> 至于将它添加到 AnchorJS，我想我会推迟，原因如下：
> 
> * [由于为可能不完全支持新剪贴板 API](https://caniuse.com/#feat=clipboard)的浏览器添加了回退， “复制到剪贴板”代码[可能会很复杂](https://stackoverflow.com/a/30810322/1154642)。对于那些不使用此功能的人，或者那些使用但不需要支持那些旧浏览器的人，我不想将这些回退的膨胀添加到 AnchorJS 中。[](https://caniuse.com/#feat=clipboard)
> * 此功能需要我添加一些新的 UI 元素，这会引发一些新问题（请参见下面显示悬停状态和确认消息的屏幕截图）。默认样式需要是什么？作者可以覆盖它们吗？什么 z-index 合适？
>   ![图片](https://user-images.githubusercontent.com/1256329/83672802-de3d4b80-a5a4-11ea-8429-639a2d9001aa.png)
> 
> 总的来说，现在为一个小众功能添加这种复杂性是不值得的。一些好的后续步骤可能是将添加此功能的要点放在一起，以便有兴趣的人可以复制/粘贴到他们自己的代码中。这甚至可以采用同级包或插件（如`anchorjs-copy-to-clipboard`）的形式。如果您感兴趣，请随意通过其中之一（除非我看到对此类功能的更多需求，否则我可能不会这样做）。
> 
> 无论如何，如果很多人最终都使用了这样的解决方法，那么也许将它引入主项目会更有意义。👍

# Hi, is there any progress in one-click copying?

**Comment by bryanbraun** [comment]
@y377, no updates... still no plans to add it to the library for the reasons described above.

I saw that you got copy-to-clipboard working in [the comment you shared here](https://github.com/bryanbraun/anchorjs/issues/188#issuecomment-1376685432), using external code. Looks pretty good!

**Comment by y377** [comment]
> @y377, no updates... still no plans to add it to the library for the reasons described above.
> 
> I saw that you got copy-to-clipboard working in [the comment you shared here](https://github.com/bryanbraun/anchorjs/issues/188#issuecomment-1376685432), using external code. Looks pretty good!

Yep, I got it, thanks for the plugin, it renders almost perfectly, and if it's considered adding hover hints and one-click copy, I can contribute!

**Comment by bryanbraun** [comment]
@y377, even if we don't add the feature to AnchorJS right now, you can still share a code snippet showing what you did in a comment (on this issue) or in a [Github Gist](https://gist.github.com/). That way, if other people want to do something similar, they can look at your code as an example.

**Comment by y377** [comment]
```js
window.addEventListener("load", event_pageLoaded, false);

/**
 * @description 页面载入事件处理事件
 */
function event_pageLoaded() {
    // 还原图标样式延时时间 1000 毫秒
    const TIMER_DEFAULT_ICON_STYLE = 1000;
    // 代码块
    var copyAnchor = document.querySelectorAll('.js-toc-content .anchorjs-link');

    // 遍历代码块添加按钮
    for (let j = 0; j < copyAnchor.length; j++) {
        // 当前命中的代码块元素 <pre> 标签
        let ele_maodian = copyAnchor.item(j);
        // let ele_btn = document.createElement("button");

        // ele_maodian.setAttribute("class", "octicon btn btn-none");
        // 生成复制按钮后添加iconfont，添加样式
        const i_maodian = document.createElement("i");
        i_maodian.classList.add(...[`bi`, `bi-paragraph`]);
        ele_maodian.appendChild(i_maodian);
        // ele_maodian.appendChild(ele_maodian.nextSibling);
        ele_maodian.setAttribute("data-clipboard-action", "copy");

        ele_maodian.setAttribute("data-bs-toggle", "tooltip");
        ele_maodian.setAttribute("data-bs-title", "点击复制");

        // 生成 鼠标悬停提示 - 实例对象
        const bs_btnTooltips_maodian = new bootstrap.Tooltip(ele_maodian);

        // 生成 ClipboardJS 实例对象
        const clipboard = new ClipboardJS(ele_maodian, {
            target: function(trigger) {
                return trigger.parentElement;
            },
        });

        // ClipboardJS 实例对象的拷贝成功事件处理函数
        clipboard.on("success", function(e) {
            // 获取当前用户点击的按钮触发元素 以及内部的i元素 ( i元素在按钮创建之初就已置入 )
            const currentTriggerElement = e.trigger;
            const i_maodiannnerIcon = currentTriggerElement.querySelector("i.bi-paragraph");
            // 控制指定元素的图标显示状态
            FN_styleChange_maodian(i_maodiannnerIcon, bs_btnTooltips_maodian, true);
            window.setTimeout(FN_styleChange_maodian.bind(null, i_maodiannnerIcon, bs_btnTooltips_maodian, false), TIMER_DEFAULT_ICON_STYLE);
            // 清除选区
            e.clearSelection();
        });
    }
}

/**
 * @description 控制指定元素的图标显示状态
 * @param {Object.Element} param_element 需要控制外观的元素
 * @param {Object.Element} param_elementTips 需要更改提示的元素
 * @param {Boolean} param_status 目标状态
 */
function FN_styleChange_maodian(param_element, param_elementTips, param_status) {
    // 默认与变动的样式
    const clissList_default = [`bi`, `bi-paragraph`];
    const clissList_changed = [`bi-check2`, `text-success`];

    // 要开启显示
    if (param_status == true) {
        // 移除默认样式，更换为新的样式
        param_element.classList.remove(...clissList_default);
        param_element.classList.add(...clissList_changed);
        param_elementTips.setContent({ ".tooltip-inner": "已复制" });

    } else {
        // 移除新样式，还原默认样式
        param_element.classList.add(...clissList_default);
        param_element.classList.remove(...clissList_changed);
        param_elementTips.setContent({ ".tooltip-inner": "点击复制" });

        param_elementTips.hide();
    }
}
```
## ⚠If you need hover tips, you need to load [popper.js](https://popper.js.org/)
