### ISSUE TITLE
Generated IDs can get too long and are not "cleaned"

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#14]
There's nothing in place to prevent generated IDs from becoming too long. This usually isn't a problem when AnchorJS is used on headings, but it surfaces when used to anchor things like paragraphs. For example, go to the demo page, open the console and run the following:

```javascript
addAnchors('p');
```

This results in links like: `http://bryanbraun.github.io/anchorjs/#-if-the-element-being-selected-has-an-id,-anchorjs-will-create-anchors-that-link-to-that-id.-for-example,-because-the-h1-above-has-an-id-of-test-id-1,-anchorjs-creates-an-anchor-link-with-an-href-of-href=`

A related issue that we see in this ^^^^ example is that we don't clean the content pulled in for use in the generated IDs. This results in a broken experience on the 2nd paragraph:

![image](https://cloud.githubusercontent.com/assets/1256329/5594409/27c55906-9218-11e4-88dd-a122ad3d24bc.png)

**Comment by remexre** [comment]
I think this was misclosed? I still get e.g. https://melt-umn.github.io/monto-v3-draft/draft01/#this-document-suggests-changes-to-the-monto-protocols-which-are

I was wondering if instead it would make sense to have `urlify` be a function of the element, rather than its `textContent`, so users could define their own `urlify` based on the location of the paragraph rather than its content. For the above paragraph, for example, I'd prefer it to have an ID of `2-p2` instead.

**Comment by bryanbraun** [comment]
Hey @remexre 👋 .

We added a feature to truncate the url, but the default length for truncation is pretty long (64 characters) which is why your URL is as long as it is. You can [adjust the length](https://www.bryanbraun.com/anchorjs/#options) to be shorter if you want.

If you really want to customize `urlify`, you can write your own and override the one that comes with AnchorJS ([see this JSFiddle for a basic example](https://jsfiddle.net/5du3m56d/1/)). That's not exactly "location-based" since it would apply to _all_ the anchors, but you could work around it by creating [multiple sets of anchors](https://www.bryanbraun.com/anchorjs/#multiple-sets-of-anchors), and using one instance to target paragraphs and another to target headings (for example).

Does some combination of those options get you what you're looking for?
