### ISSUE TITLE
how to add 2 anchors side by side?

### ISSUE THREAD

**Issue by costateixeira** [bryanbraun/anchorjs#140]
Apologies for using issues for a question - not sure this should be easy if I knew more js. 
Can I add 2 anchors with different icons and behaviour, side by side?

I want one anchor for the direct link, and another to be a "provide feedback about this section" - which can be a url, I think I can use css or even options.base for that.

Is this possible? The below is not working (and shows my lack of knowledge in js).
Again, apologies for question - I did not find a better place to ask about this.

```
    var anchors = new AnchorJS({
      visible: 'hover',
      placement: 'right',
      icon: '#'
    });
    var feedbackAnchors = new AnchorJS({
      visible: 'always',
      placement: 'right',
      icon: '?'
    });
    feedbackAnchors.add();
    anchors.add();
```

**Comment by bryanbraun** [comment]
Hey @costateixeira.

You can definitely do different types of anchors. The feedback thing is not really use-case for this project, but you could probably hack something together that redirects people to a separate feedback page (using the base option or by adding event listeners to those anchors to change their default behavior).

Here's a Codepen showing a rough example of how that could work with the `base` option: https://codepen.io/bryanbraun/pen/yLeOWrv

**Comment by costateixeira** [comment]
thanks @bryanbraun 
I wanted these two anchors to be side by side, on the same element - for each section, i have an <h3> and I want all the <h3>to have a deep anchor and a "feedback" link. would that be possible?
(sorry if I did not explain before, and thank you for the reply.)

**Comment by bryanbraun** [comment]
Oh, I see.

Yeah, sorry, but the library doesn't let you put two anchor links on the same element:

https://github.com/bryanbraun/anchorjs/blob/261c6d3e5013cc82a7682e427378f1dd89d8456d/anchor.js#L107-L110

You'll probably need to do some custom javascript in order to get what you're looking for. 😞

**Comment by costateixeira** [comment]
Thank you, and apologies for the newbie question. I'll catch up with js / jquery.
