### ISSUE TITLE
Drop jQuery from docs

### ISSUE THREAD

**Issue by XhmikosR** [bryanbraun/anchorjs#151]
AFAICT it's used only in https://github.com/bryanbraun/anchorjs/blob/master/docs/scripts.js. Everything can be replaced with vanilla JS trivially, apart from `slideToggle()`.

I guess another viable solution would be to update jQuery to the latest version.

Not a high priority, of course, just wanted to make an issue to track this. :)

**Comment by bryanbraun** [comment]
Agreed! I'd support removing jQuery and replacing slideToggle with a plain JavaScript alternative. 👍

**Comment by adrienluitot** [comment]
Hello !
I can work on it if you want :D

**Comment by bryanbraun** [comment]
@adrienluitot, be my guest! 😄

**Comment by bryanbraun** [comment]
I just merged this in https://github.com/bryanbraun/anchorjs/pull/163. This was a great improvement... thanks for the help! 🙇‍♂️

**Comment by adrienluitot** [comment]
You are welcome ! :D
