### ISSUE TITLE
Consider adding a LICENSE file

### ISSUE THREAD

**Issue by velut** [bryanbraun/anchorjs#165]
Hi,

This project is described as MIT licensed both in the Readme and package.json files, however the full license and copyright information are missing.

If a LICENSE file is present at the root of your project, npm will automatically include it when releasing your package and that can help tools like [webpack-license-plugin](https://github.com/codepunkt/webpack-license-plugin) extract licensing information.

Could you please add a LICENSE file to your project?

Thanks for your time.

**Comment by bryanbraun** [comment]
I'm on board with this. If anyone wants to submit a PR, feel free! If not, I'll get to it eventually.

**Comment by betodasilva** [comment]
Hi, @bryanbraun. Just sent a PR :smile:
