### ISSUE TITLE
Anchor link hashes not working in Chrome

### ISSUE THREAD

**Issue by twhite96** [bryanbraun/anchorjs#167]
I'm using Jekyll and have imported the library from the CDN and created a new Anchor like so:

```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.3.0/anchor.min.js"></script>

<script>
    var anchor = new AnchorJS({
      placement: 'left',
      visible: 'always'
    });
    anchor.add('#anchored > h1, #anchored > h2, #anchored > h3, #anchored > h4, #anchored > h5, #anchored > h6');
</script>
```

However, while when I click on the link icon in each header on my site, it scrolls to that header, but the hash in the url is not present. 

I feel like I am doing something wrong but not sure what.

Need some help.

Thanks.

**Comment by bryanbraun** [comment]
Hey @twhite96. 👋 

It's hard to tell what's happening without looking at an example, so I peeked at your Github profile and noticed this issue happening on [this page](https://tiffanywhite.dev/2020/10/12/real-artists-ship/).

If the hash isn't showing up in the url, usually that means something is interfering by calling `preventDefault`. Poking around your code, it looks like you might be using [this jQuery plugin for smooth-scrolling](https://github.com/kswedberg/jquery-smooth-scroll). If so, in [the options](https://github.com/kswedberg/jquery-smooth-scroll#options), it looks like you can set `preventDefault` to false.

I'll bet that takes care of it, but if not, I'll probably need some more details to help figure out what's going on.

**Comment by twhite96** [comment]
@bryanbraun I think I found the issue. The Jekyll theme I am using has a plugin called `lity.js` that messes with the url params. I am trying to figure out how to troubleshoot, or replace, the library. Any ideas? I will make the repo public so you can poke around.

**Comment by bryanbraun** [comment]
Thanks @twhite96. I was able to look at that repo and find the issue. The fix ended up being in your codebase, so I submitted a PR here: https://github.com/twhite96/tiffany.blog/pull/8

It doesn't look like this will require an update to AnchorJS, so I'm going to go ahead and close this issue. We can move the discussion over to the PR in your repo if you have any other questions. 👍
