### ISSUE TITLE
Anchor icon is always visible on Windows when visible=touch after promoted to v4.3.0

### ISSUE THREAD

**Issue by v-pegao** [bryanbraun/anchorjs#168]
**Issue description**

We identified a behavior change after promoted Anchorjs from v4.2.2 to v4.3.0. 

 We are using `visible: touch` as anchor options. For `v4.2.2`, the anchor ![image](https://user-images.githubusercontent.com/25164547/103971353-48eedf00-51a5-11eb-9515-863ea8fb476a.png) is `hover` on page of `Windows10`, after promoted to `v4.3.0`, the anchor ![image](https://user-images.githubusercontent.com/25164547/103971353-48eedf00-51a5-11eb-9515-863ea8fb476a.png) is `always` there instead of `hover`.

Here are sample pages to help understand the issue:
_v4.2.2 page(hover)_: https://kleisauke.github.io/net-vips-tests/api/NetVips.html
_v4.3.0 page(always)_: https://kleisauke.github.io/net-vips/api/NetVips.html

**Operating System**: Windows

**AnchorJs version**: 4.3.0

**Expected Behavior**:
AnchorJS links only become visible when hovering over the headings like before for Windows when visible is touch.

**Actual Behavior**:
AnchorJS links are always visible for Windows when visible is touch.

**Note:**
This behavior change seems related to the newly added condition `window.TouchEvent` in function `isTouchDevice()` with [this commit](https://github.com/bryanbraun/anchorjs/commit/409cc0957a145d09dc77f38552631fd12e69a4c3#diff-a294f8c40575a70a0103eac2942100cd02d3b4ca9a3957433e1fd5da3b813af5R8)

> isTouchDevice() for v4.3.0:
this.isTouchDevice=function(){return Boolean("ontouchstart"in window||**window.TouchEvent**||window.DocumentTouch&&document instanceof DocumentTouch)}

> isTouchDevice() for v4.2.2:
,this.isTouchDevice=function(){return!!("ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch)}

**Comment by bryanbraun** [comment]
Thanks for the detailed report. You're totally right about where that new behavior is coming from.

Unfortunately, the behavior you're seeing is intended. To quote the docs:

> `touch` will always display anchors for devices that support touch events, and only display them via hover for devices that do not support touch events. This approximates touchscreen detection (but [isn't 100% accurate](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/)).

If you're seeing the links in your browser on Windows 10, that means your browser supports touch events (more specifically, `window.TouchEvent`). That might mean your desktop/laptop has support for touch interface (many windows computers, like surface books, do), or that the browser would support a touch interface if it were installed on such a device.

The change that you saw in the newer AnchorJS version comes from a similar Modernizr update, which was intended to make touch event detection more accurate. You can see details on that here: https://github.com/Modernizr/Modernizr/pull/2409

Ultimately, I'm comfortable leaving this feature as-is, focused on detecting touch-events, which only approximates touchscreen detection. The alternative is to remove the feature altogether (which is [what Modernizr eventually did](https://github.com/Modernizr/Modernizr/pull/2432)).

If you prefer the former behavior, I'd say feel free to continue using v4.2.2.

**Comment by v-pegao** [comment]
Thanks for the reply, closing the issue now

**Comment by KasparEtter** [comment]
`Boolean('ontouchstart' in window || window.TouchEvent || window.DocumentTouch && document instanceof DocumentTouch)` returns true in the current Chrome (Version 105.0.5195.125) on my old MacBook Pro, which doesn't have a touch screen. The new behavior is unacceptable to me, so I will have to stay on v4.2.2. 😕
