### ISSUE TITLE
Add more than one kind of anchor with different options/properties

### ISSUE THREAD

**Issue by bw2** [bryanbraun/anchorjs#194]
Thanks for the really nice library!

Just in case this is easy to do, is it possible to add both to the same page:
a) always-visible anchors with default link icon for h3 and h4 tags
b) on-hover anchors with P icon for paragraphs

**Comment by bryanbraun** [comment]
Yes, @bw2, this is possible. Checkout this example in the docs: https://www.bryanbraun.com/anchorjs/#multiple-sets-of-anchors.

In your case, it might look something like this (untested):

```js
const headingAnchors = new AnchorJS({
  visible: 'always'
});
headingAnchors.add('h3, h4');

const paragraphAnchors = new AnchorJS({
  placement: 'left',
  icon: '¶',
  visible: 'hover'
});
paragraphAnchors.add('.main p');
```

**Comment by bw2** [comment]
Missed that part of the docs. Thank you - it works!
