### ISSUE TITLE
Get this awesome plugin on jsdelivr's CDN!

### ISSUE THREAD

**Issue by chauncey-garrett** [bryanbraun/anchorjs#25]

**Comment by bryanbraun** [comment]
Seems like a good idea once we get to 1.0.

Any specific reason to recommend jsdeliver? I know there are other CDNs (like [CDNJS](https://github.com/cdnjs/cdnjs)) that we could also approach. Maybe we go for both? A whole bunch?

We probably don't want to go too crazy, so as to reduce release overhead (at least to begin with).

**Comment by chauncey-garrett** [comment]
I use jsdelivr for it's low latency ([based on this data](http://www.cdnperf.com)). The content is delivered by MaxCDN and Cloudflare.

> jsDelivr is a public open-source CDN where anyone can submit a project to be hosted and delivered by our network. Most people probably know that Google hosts jQuery and a few other popular libraries.

> We don’t look at the popularity of the project to approve it for inclusion in jsDelivr. Plus a lot more types of projects are allowed, like CSS frameworks, fonts, WordPress plugins etc.

> **And by using GitHub, we allow the community to fully interact with jsDelivr by adding and updating files.**

*Emphasis added.* See [this page](http://www.jsdelivr.com/about.php) for more.

Perks:

- Initial submit is a [pull request](https://github.com/jsdelivr/jsdelivr#how-to-submit-or-update-projects).

- After that, keeping the project updated is done through a [JSON file](https://github.com/jsdelivr/jsdelivr#auto-updating).

From there, it's largely hands-off!

**Comment by bryanbraun** [comment]
It's now on jsDelivr (see https://cdn.jsdelivr.net/anchorjs/1.1.1/anchor.min.js).

Closing this issue.

**Comment by chauncey-garrett** [comment]
Thanks!
