### ISSUE TITLE
Think about providing configurable options.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#26]
I can see how some might want configurable options for anchor links. For example:
- Specifying which symbol is used (Default link icon, ASCII/Unicode character, base-64 encoded image, etc). This is mentioned in #23.
- Specify whether the link icon is initially visible or only visible on hover.
- Specify if the icon is on the left or right of the element it is connected to.

All of these options (and more) could be wrapped into a configuration object (or some other scheme) for configuring the links. We can look to other small utilities for good examples on setting configuration like this.

**Comment by chauncey-garrett** [comment]
+1 for configurable options. I'm always for increasing ease of use. Speaking of which, what is the currently recommended way to specify whether the icon is on the right or left of it's connected element?

**Comment by bryanbraun** [comment]
Currently, there's no configurable option to specify right or left. The anchor [is always appended after the element text](https://github.com/bryanbraun/anchorjs/blob/gh-pages/anchor.js#L82), which leads it to be displayed to the right by default (arguably, the most common use case).

You can work around this with CSS:

![image](https://cloud.githubusercontent.com/assets/1256329/6883103/ac2c552e-d574-11e4-9dbc-f6dd63f29357.png)

...but that styling is not particularly robust.

**Comment by chauncey-garrett** [comment]
Thanks for the CSS snippet. I agree, it's not very robust at all. I do like having the anchor on the left though as it provides a consistent location to find it rather than zig-zagging across the page according to the length of the preceding text.
