### ISSUE TITLE
Add an exception class

### ISSUE THREAD

**Issue by chauncey-garrett** [bryanbraun/anchorjs#32]
Something like `.not-anchored` or `.unanchored` so that anchor links can be overridden.

**Comment by Johann-S** [comment]
Or simply add an array of unwanted anchors like this : 
``function addAnchors(selector,unWantedAnchors)``

**Comment by bryanbraun** [comment]
@Johann-S,

Thanks for the suggestion. I see how this could be useful, and I intend to add the feature. As for your PR, I'm working on a 1.0 version that includes this feature, and it will change the API. As such, the implementation will look a bit different than the one in your PR. Currently, it's planned to look more like this:

```javascript
anchors.add('h2, h3, h4');
anchors.remove('.subMenu');
```

I'll keep you updated on the progress.

**Comment by Johann-S** [comment]
Ok that's good thank you.
I also thought about to set a CSS class which will disable AnchorJS like ``noAnchor``. Before adding your anchor to the element you can check if this element have this class or not.
I'm not sure if it's the best things to do or not.
