### ISSUE TITLE
International & UTF-8 encoded characters are removed

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#41]
From Bartosz Wójcik:

> Hi Bryan, I'm testing AnchorJS on my site and have found a bug.
> 
> AnchorJS generates invalid entries for UTF-8 encoded national characters, for example
> .... Źródła
> 
> (this is in polish - "sources")
>
> The generated anchor link omits the national letters and generates id="rda"

**Comment by bryanbraun** [comment]
Removing unicode characters was a deliberate choice, even when international characters are being used (for example, see https://github.com/bryanbraun/anchorjs/pull/30#issue-64220879)

I'm open to reconsidering the approach. There are technical reasons that actual unicode characters don't belong in URLs, but we could [percent-encode them](http://stackoverflow.com/a/2742985/1154642), which displays as unicode in the URL bar of modern browsers.

One challenge there is where do we draw the line? Do we percent-encode spaces? Punctuation?

I'll have to think about the pros/cons of this change. The goal of it would be to make more meaningful, readable URLs, but percent-encoded URLs might actually be less readable in a lot of cases, like when dropped in an email or chat program.

If anybody has thoughts, feel free to weigh in.

**Comment by bryanbraun** [comment]
> When I thought about it it seems right, transliteration is hard, the
> best I saw is from WordPress, if you mind you could look at the source
> of:

> https://codex.wordpress.org/Function_Reference/remove_accents

> Recently I've been adding it to the Invision Power Board (they decided
> not to use transliteration in the v4 forum software), so I know the
> pain behind the % ;)

> You could use this remove_accents() function code (it's really simple)
> to convert it to JS and add it to your code, it would be a great asset
> to your library for any non-english website.

> I've been looking for this kind of library for my Yii2 application but
> finally I've been able to identify it on Bootstrap's homepage ;), I
> think this would be a great addition to Bootstrap itself.

> Bartosz Wójcik

**Comment by bryanbraun** [comment]
Ooh. I'm interested in that idea of running the text through a function that converts accented characters to ASCII. I like that a lot better than percent encoding. The idea of making IDs with percents all over the names makes me uncomfortable.

It looks like many people have already written Javascript solutions for this: http://stackoverflow.com/a/18391901/1154642 

This would only solve some of the problem. Many characters (like Cyrillic letters or Japanese Kanji) won't be fixed by this solution. I'll have to think about whether this improves the situation enough to offset the additional page-weight (which isn't that much, but we're trying to keep this super light).

**Comment by thecotne** [comment]
> Ooh. I'm interested in that idea of running the text through a function that converts accented characters to ASCII.

translating other languages to Latin is as stupid as translating Latin to something else
(i understand it's ASCII and ... but it is wrong)

you just need to remove some special chars like this 
https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/html.c#L274

github does that 
wikipedia does same 
it's more SEO friendly 

> I like that a lot better than percent encoding. The idea of making IDs with percents all over the names makes me uncomfortable.

you don't need to convert unicode characters to some weird encoding like `percent encoding` (which was bad idea when it was created)
unicode is supported in html (including id attribute)

@bryanbraun btw thx for this plugin i am using it in my blog https://devtime.ge/
i am generating ids with [redcarpet](https://github.com/vmg/redcarpet) and it works perfect 

i can submit pull request for `redcarpet` like implementation of unicode support

**Comment by bryanbraun** [comment]
These are great thoughts. I think we should go with that approach.

I don't work often with non-latin characters so thanks for providing some perspective.

**Comment by bryanbraun** [comment]
@thecotne (and anybody else), I've put up a PR to fix this: https://github.com/bryanbraun/anchorjs/pull/42

It will preserve unicode characters, only filtering out these non-safe ones (I pulled the list straight from the redcarpet code you referenced): ``& +$,:;=?@"#{}|^~[`\%!']./()*\``

Take a look and if nobody opposes, I'll merge sometime next week.

**Comment by thecotne** [comment]
@bryanbraun i can't find test case for non latin strings
also there is no separate function for converting string to id to test it

i don't like idea of manually testing code since unit tests are like documentation of behavior without it behavior can change in future without anyone noticing

**Comment by bryanbraun** [comment]
@thecotne, good call and thanks for the suggestions. I've pulled it out into a separate function and I wrote some tests against it in 817de15 (which was added to the PR).

How does that look?

**Comment by thecotne** [comment]
looks good :+1:

**Comment by thecotne** [comment]
> truncate to 64 characters
https://github.com/bryanbraun/anchorjs/blob/international/anchor.js#L163

is this really necessary?
also i don't see tests for this behavior 
i would like to see this optional

it's good enough to merge anything else can be changed with minor updates

**Comment by bryanbraun** [comment]
@thecotne, thanks for looking it over. Planning to merge soon.

As for the 64 character truncate, the main use-case is for [anchoring to paragraphs](http://scripting.com/2014/02/23/designChallengeParagraphlevelPermalinks.html) without having an entire paragraph in an ID. Instead of making it optional, I'd rather make truncate longer if you find the current truncate limiting (maybe 75 chars? 90 chars?). You are right that it's not tested clearly... I'll plan on writing more specific tests for that in a future PR.

**Comment by thecotne** [comment]
it will be better to have that optional 
may be someone wants it to be 10 chars or someone wants it to be 120 chars 
you can't have one value to fit them all and when it's so simple to have it optional and so cover any possible use case why not?

as for default value i don't have anything against 64 (looks random to me but it's okey)

**Comment by bryanbraun** [comment]
@thecotne, thanks for the suggestion. I merged the code but also added `options.truncate` to v2.0.0 so people can set it to something other than the default 64. More info here: http://bryanbraun.github.io/anchorjs/#options
