### ISSUE TITLE
Provide a way to not append auto-increment ID to URLs

### ISSUE THREAD

**Issue by mondalaci** [bryanbraun/anchorjs#44]
Please consider the following responsive markup:

```
<div class="row large-feature" id="increased-ergonomics">
    <div class="col-md-8">
        <h2 class="visible-xs visible-sm anchored">Increased Ergonomics</h2>
        <img src="/wordpress/wp-content/uploads/increased-ergonomics-cord.jpg" alt="Increased ergonomics" width="1200" height="473">
    </div>
    <div class="col-md-4">
        <h2 class="hidden-xs hidden-sm anchored">Increased Ergonomics</h2>
        ...
    </div>
</div>
```

In this case `#increased-ergonomics-1` and `#increased-ergonomics-2` gets generated respectively. I'd like to disable this behavior and make anchor.js not append the auto-increment IDs after URLs.

Or is there any way to achieve this behavior right now?

**Comment by bryanbraun** [comment]
@mondalaci, thanks for the example.

If you don't like the id's being generated by AnchorJS, you can add distinct ID attributes to your h2's and anchorjs will use them. For example:

```
<h2 class="visible-xs visible-sm anchored" id="ergonomics">Increased Ergonomics</h2>
```
...will link to `http://www.example.com/example-page#ergonomics` when the anchor is clicked.

I could alter how AnchorJS generates ids / hash names, but I can't think of any use-case where you want duplicate IDs on a page. If you had duplicates then it would probably cause unexpected behaviors (like jumping to the unintended part of the page). Let me know what you think.

**Comment by bryanbraun** [comment]
Haven't heard back so I'm going to close this for now. Feel free to reopen if my answer wasn't helpful or you have more to say on the topic. :+1:

**Comment by mondalaci** [comment]
Sorry for the lack of reply, Bryan. Yours seems like the perfect solution. Thank you very much!
