### ISSUE TITLE
default to showing anchor links on touch devices

### ISSUE THREAD

**Issue by afeld** [bryanbraun/anchorjs#47]
Great plugin! I just played with adding the plugin to [a site](https://pages.18f.gov/before-you-ship/), and figured "hey, on touch devices, it won't be possible to hover over headers to get the anchor links". I added (essentially) the following:

```javascript
var isTouchScreen = function() {
  // https://github.com/Modernizr/Modernizr/blob/da22eb27631fc4957f67607fe6042e85c0a84656/feature-detects/touchevents.js#L40
  return ('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch;
};

if (isTouchScreen()) {
  anchors.options = {
    visible: 'always'
  };
}
anchors.add();
```

but this seems like a reasonable default behavior...wondering if there's interest in incorporating it into the plugin, or at least adding a note in the README. Thoughts?

**Comment by bryanbraun** [comment]
I like this idea and it's not a lot of code.

The current visibility options are `always` and `hover` (which technically includes focus). `hover` is the default. We can easily add a third option that's `hover` on cursor devices and `always` on touch. We can add the option in a minor version, though making it default would require a major version increase.

I'll start on a PR for simply adding the option.

The more I think about it, I like the idea of it eventually being default. I'd be interested to hear if anybody else would prefer that as well.

What to call the option? `touch`? `hybrid`? `contextual`?

**Comment by bryanbraun** [comment]
I've gone ahead and added an option called `touch` that produces this behavior. It can be enabled like this:

```javascript
anchors.options.visible = 'touch';
```

The default value remains `hover` for now, but I expect to change it to `touch` next time I do a major version update.

Closing the issue. :+1:
