### ISSUE TITLE
Nuget Request

### ISSUE THREAD

**Issue by amastaneh** [bryanbraun/anchorjs#51]
Would you please add `anchor-js` [NuGet](http://nuget.org) package. It's really useful for Microsoft software developers. You can find a less than a hour solution to build and deploy NuGet package in here http://docs.nuget.org/docs/creating-packages/using-a-gui-to-build-packages

Thank you ;-)

**Comment by bryanbraun** [comment]
Hey, I looked into this a bit.

In short, I don't think I can take on the responsibility to make the Nuget package and keep it updated at the moment.

I'm one maintainer, and I've typically made updates pretty frequently. I've looked into ways to automate a Nuget deployment, but I haven't found one that would literally be as easy as a terminal command (without bringing in workflow overhead like `gulp`, etc). Anything more complicated would feel like more burden than it's worth.

Looking at similar requests (https://github.com/twbs/bootstrap/issues/16692), it looks like ASP.NET developers using Visual Studio 2015 are [moving towards using Bower](http://docs.asp.net/en/latest/client-side/bower.html) for client-side libraries. So over time, the need to have an anchorjs package on NuGet will go down.

I get that enterprises may lag a bit behind the newest tools, so if you or somebody else wants to publish a NuGet package for anchorJS and keep it relatively up to date, I'm fine with that. But I'm not too interested in adding that process for myself right now.
