### ISSUE TITLE
Generate the text banner automatically.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#54]
Each time we update AnchorJS, we have to update a text banner at the top of `anchor.js` and `anchor.min.js`. It's a manual process, where we increment the version number, date, and copyright for each release:

```js
/**
 * AnchorJS - v3.1.0 - 2016-02-12
 * https://github.com/bryanbraun/anchorjs
 * Copyright (c) 2016 Bryan Braun; Licensed MIT
 */
```

I'd like to automate this process. Ideally, we would change the "release" task in `package.json` so running `npm run release` dynamically generates the new text banner, in addition to everything else it already does.

There are plugins that already do this (like [grunt-banner]). I'd like to find one that isn't grunt-specific.

Edit: This one looks promising: https://github.com/jonschlinkert/add-banner

[grunt-banner]: https://github.com/mattstyles/grunt-banner

**Comment by bryanbraun** [comment]
This one looks promising: https://github.com/jonschlinkert/add-banner

**Comment by thecotne** [comment]
@bryanbraun i am not big fan of low quality packages and did not wanted to add gulp or grunt so i have my own implementation of banner generator

**Comment by thecotne** [comment]
@bryanbraun ping

**Comment by bryanbraun** [comment]
Ah yes, sorry I forgot to respond.

I see your PR. Thanks for contributing. 😄  I should be able to review it tomorrow. 👍
