### ISSUE TITLE
Add a tooltip?

### ISSUE THREAD

**Issue by mstanleyjones** [bryanbraun/anchorjs#55]
I think this should be pretty easy, but I'd like a way to add tooltip text that just says 'Permalink'. I was having a look at http://www.w3schools.com/css/css_tooltip.asp but can't figure out how to add the <div> to the output when using anchor.js. I tried a Google but couldn't find anyone ever asking this question so I thought I'd ask it!

**Comment by bryanbraun** [comment]
You should be able to add some styles that gives you something close to what you're looking for. Maybe similar to this? http://codepen.io/bryanbraun/pen/ZWxZWV?editors=0110

**Comment by bryanbraun** [comment]
@mstanleyjones, I tweaked my example to include the tooltip triangle, and used `ex` units so it scales based on the heading size: http://codepen.io/bryanbraun/pen/ZWxZWV?editors=0100
