### ISSUE TITLE
Fails when a header empty is empty

### ISSUE THREAD

**Issue by tmcw** [bryanbraun/anchorjs#56]
![2016-04-29 at 11 43 am](https://cloud.githubusercontent.com/assets/32314/14921318/a5b3d856-0dff-11e6-852e-732530bb06c4.png)

Produced by the following html:

```html
<h3 class='mb0 no-anchor'></h3>
```

And JavaScript

```js
anchors.options.placement = 'left';
anchors.add('h3');
```

**Comment by bryanbraun** [comment]
Ah... good catch. Looks like a regression that was introduced in the last release. Working on a fix. 👍
