### ISSUE TITLE
Add export for Node (e.g. UMD)

### ISSUE THREAD

**Issue by adjohnson916** [bryanbraun/anchorjs#59]
Please support Node by attaching to `module.exports`. A favorite pattern is [`returnExports` from UMD](https://github.com/umdjs/umd/blob/master/templates/returnExports.js) which lets a module work with Node (CommonJS), AMD (e.g. RequireJS) and browser globals. I can submit a PR if this sounds good.

**Comment by adjohnson916** [comment]
Fixed by #60.

**Comment by bryanbraun** [comment]
Nice! I've been meaning to look into this.

I should be able to go through these changes sometime in the next week.

**Comment by adjohnson916** [comment]
@bryanbraun Thanks for merging. For npm support we still need #61.
