### ISSUE TITLE
Use fallback fonts for IE8

### ISSUE THREAD

**Issue by XhmikosR** [bryanbraun/anchorjs#6]
After testing things on IE8, `setAttribute` seems to work fine. Only issue with anchorjs at this point is the font.

https://github.com/CSSLint/csslint/wiki/Bulletproof-font-face

**Comment by bryanbraun** [comment]
I've decided not to bring in fallback fonts for IE8, due to the added complexity for implementers who would need to include them.

I'm open to other suggestions on ways to improve graceful degradation for IE < 9. Feel free to open a new issue if you have ideas for that.
