### ISSUE TITLE
Document that anchorjs requires <!doctype html>

### ISSUE THREAD

**Issue by mhils** [bryanbraun/anchorjs#65]
It took me quite a bit of debugging to realize that anchorjs' `hover` mode requires a
```
<!doctype html>
```
at the beginning of the document. Otherwise browsers will fall into some compatibility mode and `*:hover > .anchorjs-link` won't match. Of course, you should always specify the doctype, but my 5 minute hack didn't. :innocent:  Realizing that this was caused by a missing doctype was not really straightforward :smile: .

Thanks for the great project!

**Comment by bryanbraun** [comment]
Woah, I didn't know that mattered. But, yeah I'm seeing the same thing in Chrome. I wish I knew more about why this is happening (so I could document it correctly). Did you find any docs or blogposts explaining it clearly? I might have to do some digging.

**Comment by bryanbraun** [comment]
Did some looking into this, and according to [this description](http://stackoverflow.com/a/6076470/1154642), leaving off the doctype in modern browsers causes them to load in quirks mode, where any number of modern techniques may not work.

I'm realizing there's not much that's AnchorJS specific about this browser-behavior, so I'm not sure it makes sense in on the main docs.

I'm glad you created the issue though. Hopefully anybody else who encounters this, will find our conversation and understand what's happening. 👍

**Comment by davidjb** [comment]
👍 for the info.  In my case, it was an errant character before the doctype declaration which was causing the browser to start processing HTML, and thus in quirks mode.
