### ISSUE TITLE
Replace characters

### ISSUE THREAD

**Issue by rafalolszewskii** [bryanbraun/anchorjs#72]
`What’s` is not replaced. Could be nice to do replace `'s` for `-is-`

**Comment by bryanbraun** [comment]
Just to make sure I understand...

Currently AnchorJS converts sentences like this:

`What's the big idea?` --> `whats-the-big-idea`

Are you requesting it to work like this?

`What's the big idea?` --> `what-is-the-big-idea`

**Comment by bryanbraun** [comment]
Currently the text->url code is language-agnostic. If we change `'s` -> `-is`, we're making an assumption that it's English, and introducing opportunities for edge-case bugs  in other languages. Trying to do language detection in a small utility like this is probably not a good idea.

`'s` is also used for possessives in English. So this could be a bug:

`I am going to Bob's house` -> `i-am-going-to-bob-is-house`.

Ultimately, I'd say this is a tough thing to implement well, and the benefits it would bring wouldn't be worth the cost.

I'll close this for now, but feel free to continue commenting if you have further recommendations.
