### ISSUE TITLE
Add Syntax Highlighting to the Docs

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#74]
I've had positive experiences with http://prismjs.com/ for syntax highlighting. We should use it to highlight the code snippets in the docs at http://bryanbraun.github.io/anchorjs.

I'd like to use a dark theme. Like PrismJS's Okaida.

Changes will need to be made to the gh-pages branch.

**Comment by kushalpandya** [comment]
I could work on that! PR coming soon 😃

**Comment by bryanbraun** [comment]
Fixed by #77. 🎉
