### ISSUE TITLE
Remove `H1` from the default selector.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#75]
Currently the default selector (if one isn't provided), is to add anchors to all headings: `'h1, h2, h3, h4, h5, h6`.

In practice, I've never seen anybody who wanted an anchor link on their H1, and I've seen several cases where adding one there had unintended consequences that weren't caught by the implementer. Let's remove it from the default. The new default should be: `h2, h3, h4, h5, h6`.

We'll need to:
- Change the default in the code on `master`.
- Update the docs (on the `gh-pages` branch) that mention the default.
- Check our tests, docs, and examples to make sure it doesn't break our existing code.

**Comment by kushalpandya** [comment]
I can try on this one.

**Comment by bryanbraun** [comment]
I've got some time today and will take a crack at this.

**Comment by bryanbraun** [comment]
I've got it working and will push up the change to master.

I won't update the docs until we release a new major version of AnchorJS so as to not cause confusion. Leaving this issue open until that happens so I don't forget. 😛
