### ISSUE TITLE
Edge case: anchor chaining produces error when no anchors are added.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/anchorjs#79]
**To reproduce:**
1. Browse to a page with no H2s.
2. Run this:
```js
anchors.add('h2').remove('.no-anchor');
```
3. You will see an error. Ideally this would fail gracefully if no anchors were found in the first method.

**User Impact:**
None. It only errors in cases where no anchors needed to be added (or removed in the first place). Fixing this will just clean up the console.

**Ideas:**
- [ ] Fix the code so it fails gracefully or returns early if no anchors were found.
- [ ] Update the docs to encourage using `:not()` syntax.
- [ ] Improve docs on chaining: It might be good to describe more how chaining works in the docs (simply saying that `anchors.add()` returns a copy of anchors, that you can use to run more commands).
  * Note: the chaining example in the docs says `.h1` instead of `h1` which is probably a typo.

**Comment by thecotne** [comment]
actually this must work like you can always chain jquery even if nothing is selected it returns jquery instance with empty array and all functions just try to map/forEach empty array and error does not occur 


about example
```js
// why not
anchors.add('h2:not(.no-anchor)');
```

**Comment by bryanbraun** [comment]
@thecotne, yes, I was thinking of the solution behaving like the one you mentioned for jquery.

That `:not` syntax is interesting. It might be nice to rely entirely on that and remove all the `.remove()` code. It's more efficient to use a targeted selector than to "add and then immediately remove" anchors. I certainly think it's worth adding to the documentation.

 I wonder if there are any cases where `.remove()` works where `:not` wouldn't. Perhaps if you need to add anchors, use them, and remove them at a later time? Maybe in like a single page app?

If those cases exist, I'd say it's best to keep `.remove()` in the API, but do a better job of documenting `:not` as the preferred way of excluding some targeted elements.

**Comment by thecotne** [comment]
removing `remove` will introduce major change and may break someones workflow 

let's just improve documentation and fix bug about chaining

also it would be nice to have docs in docs folder in master branch and maybe rewritten with Jekyll

**Comment by bryanbraun** [comment]
@thecotne, I created https://github.com/bryanbraun/anchorjs/issues/82 for the docs folder suggestion. We could do jekyll someday but the site is really simple, so I'd say moving the existing docs into a docs folder is good improvement for now.
