### ISSUE TITLE
Using id attribute from parent element

### ISSUE THREAD

**Issue by qqilihq** [bryanbraun/anchorjs#87]
I have a page structure like this:

```
<section id="section1">
  <h3>Section 1</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</section>
```

Is it possible to apply AnchorJS to the `h3` elements, while using the existing `id` from its parent `section`?

The obvious solution `anchors.add('section h3');` would generate new `id` attributes for the `h3` tags which I would like to avoid. And using `anchors.add('section');` will add the anchors after the section and no the the `h3`.

**Comment by bryanbraun** [comment]
@qqilihq, I thought about this for a bit and I can't think of any way to get what you're looking for with the way AnchorJS currently works.

I think your situation is unique enough that I'd recommend adding a custom links into your templates that work with your section IDs. Good luck!

**Comment by bryanbraun** [comment]
WAIT! I just remembered! We recently added a feature for these kinds of situations that hadn't been documented (or released) yet!

In short, you can use a `data-anchor-id` attribute pointing to the `id` you want it link to:
```html
<section id="some-section">
    <h2 data-anchor-id="some-section">Some section</h2>
</section>
```

There's more details [in that PR](https://github.com/bryanbraun/anchorjs/pull/83). You can find the code in the master branch, but it isn't in a release yet. Let me see if I can get a new release (and updated docs) out this weekend.

**Comment by qqilihq** [comment]
@bryanbraun Hey Brian, thank you so much for your efforts! (in the meantime I have actually solved my problem by writing the necessary attributes through the template, as you suggested).

Still: I (and probably other users as well) would be very interested in that feature! So I'm looking forward to the next release.

Many thanks so far!

**Comment by bryanbraun** [comment]
Ok, [I just released 4.0.0](https://github.com/bryanbraun/anchorjs/releases/tag/4.0.0), and the docs for this new feature can be found here: https://www.bryanbraun.com/anchorjs/#section-ids. Let me know if there are any other questions.

**Comment by qqilihq** [comment]
@bryanbraun Thanks again, Bryan! I'm currently on holidays, but I'll give it a try as soon as I'm back. Will give feedback here!

**Comment by qqilihq** [comment]
Works great! Thumbs up!
