### ISSUE TITLE
Documentation is not available

### ISSUE THREAD

**Issue by mrkkrp** [bryanbraun/anchorjs#88]
http://www.bryanbraun.com/anchorjs#examples

**Comment by bryanbraun** [comment]
Hi @mrkkrp. 👋  What exactly is the problem you're finding? I'm able to see documentation/examples at that link. 😕

**Comment by mrkkrp** [comment]
That's weird, here is what I see:

![anchorjs-docs](https://cloud.githubusercontent.com/assets/8165792/26733327/2ea267d8-47c3-11e7-9d64-9af33c251f75.png)

**Comment by mrkkrp** [comment]
If you believe that it does not affect other users, feel free to close the issue. I've read the docs from the repo itself locally.

**Comment by thecotne** [comment]
Link works for me ...

**Comment by bryanbraun** [comment]
Anybody else having trouble seeing this?

**Comment by bryanbraun** [comment]
Closing since we haven't been able to reproduce the issue. Please re-open if anybody else sees it or has more details.

**Comment by mrkkrp** [comment]
FTR, it works for me now!
