### ISSUE TITLE
Don't add duplicate IDs for anchors without IDs

### ISSUE THREAD

**Issue by XhmikosR** [bryanbraun/anchorjs#9]
So, for the IDs we generate, we should make sure they are unique. Not sure what the performance penalty will be or how exactly to do it, but it shouldn't be hard, in theory.

**Comment by bryanbraun** [comment]
I think this is a great idea, but you're right... we should keep an eye on performance.

One approach could be to query the DOM for each ID we generate, to make sure nothing is there already. This seems like it could cause a performance hit if we're generating a lot of IDs.

Maybe there's a way to pull all the the IDs in the DOM with one query, check against that list with each new generated ID, and add new generated IDs to the list as we go. Seems like that might be lighter weight.
