### ISSUE TITLE
Generated IDs should be cleaned of URL-unsafe chars such as newlines

### ISSUE THREAD

**Issue by Quuxplusone** [bryanbraun/anchorjs#94]
I tried adding deep anchor links to all my paragraphs, like this:

    new AnchorJS({
      placement: 'left',
      visible: 'hover',
      icon: '¶',
    }).add('p');

but unfortunately that produced anchor links with `href`s such as: `https://quuxplusone.github.io/blog/2018/05/10/regular-should-not-imply-default-constructible/#except-that-that’s-ridiculous-note-in-passing-that-we-cannot
use`
Neither Safari nor Chrome can handle that kind of link.

Notice the embedded Unicode smart quote `’` (which is not the problem) and the embedded newline between the words `cannot` and `use` (which is the problem).  I'd prefer if anchorjs could filter out both kinds of characters, but at least filtering out non-printable characters like newline would be appreciated because then the links would work.

My recommended patch is to change

      var nonsafeChars = /[& +$,:;=?@"#{}|^~[`%!'<>\]\.\/\(\)\*\\]/g,

to simply

      var nonsafeChars = /[^A-Za-z0-9._-]/g,

which will exclude non-printable characters as well as non-ASCII characters.

A more conservative fix could just be to add `\n\t\b\v` into the existing `nonsafeChars`.

**Comment by bryanbraun** [comment]
Good suggestions here @Quuxplusone. I'm on board with either of these, really. The simplicity of the 2nd is nice, but it would probably change previously valid urls for some people, so that'll be a major version bump. I'm fine with that, but I'll need to do some testing and might not get around to it immediately.

**Comment by bryanbraun** [comment]
That sounds good. I'm working on it now, and should have a patch release up soon.

Looking closer here, I probably won't go with your 2nd suggestion in the future. I remembered that [the URLs are designed to support most unicode characters](https://github.com/bryanbraun/anchorjs/blob/master/test/spec/AnchorSpec.js#L315-L328), so we can build unique links for content in other languages (like those using Chinese characters or the Cyrillic alphabet).

**Comment by Quuxplusone** [comment]
Makes sense. Another possibility would be to encode the non-ASCII characters (URL-encode or punycode or whatever); but I recall now that Wikipedia URL-encodes its anchor links, and I've always thought that it made them really ugly to look at.
https://phabricator.wikimedia.org/T75092 has some info on what Wikipedia does. Someone there claims that "it's HTML4 baggage."
