### ISSUE TITLE
LibreJS license comment missing

### ISSUE THREAD

**Issue by theel0ja** [bryanbraun/anchorjs#99]
Guide: https://www.gnu.org/software/librejs/free-your-javascript.html

<img width="438" alt="screen shot 2018-09-17 at 16 51 30" src="https://user-images.githubusercontent.com/5832930/45627159-f4863980-ba99-11e8-8078-3f7c223791ea.png">

Releated to this file:
https://github.com/bryanbraun/anchorjs/blob/ac306bcfc378a3593c1bbdad8af6631cf3812c3c/banner.js#L1-L17

**Comment by bryanbraun** [comment]
Wow, I didn't know this was a thing.

I could see us doing this. As such, I'd prefer to use the "[magnet link form](https://www.gnu.org/software/librejs/free-your-javascript.html#magnet-link-license)" so I don't have to include the full text of the license in a minified file. [According to Wikipedia](https://en.wikipedia.org/wiki/MIT_License#License_terms), I use the "Expat" variation of the MIT license, so I think it would look like this:

```js
/** 
  * AnchorJS - v4.1.1 - 2018-07-01
  * https://github.com/bryanbraun/anchorjs
  * Copyright (c) 2018 Bryan Braun; Licensed MIT
  */ 
// @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&dn=expat.txt MIT
... [script is here] ...
// @license-end
```

Does that look right to you?

**Comment by theel0ja** [comment]
Yes.

**Comment by bryanbraun** [comment]
Cool, just tested it out and it's working great:

![image](https://user-images.githubusercontent.com/1256329/49323594-d30aea80-f4eb-11e8-80f0-3c3cf2f1fd2d.png)

Pushing up the commit now. The license reference will get added to the next published version 👍.
